image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

variables:
  SECURE_LOG_LEVEL: info
  DOCKER_DRIVER: overlay
  CONTAINER_RULE_CRAFT: smartcommunitylab/smartergame-rulecraft:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_RULE_CRAFT_LATEST: smartcommunitylab/smartergame-rulecraft:$CI_COMMIT_REF_NAME-latest
  AUTH0_SECRET: "$AUTH0_SECRET"
  AUTH0_CLIENT_ID: "$AUTH0_CLIENT_ID"
  AUTH0_CLIENT_SECRET: "$AUTH0_CLIENT_SECRET"
  AUTH0_BASE_URL: https://frontend.smartergame.smartcommunitylab.it
  NEXT_PUBLIC_BACKEND_URL: "https://backend-smartgame.polyglot-edu.com/"
  NEXT_PUBLIC_SMARTGAME_URL: "https://smartgame-api.polyglot-edu.com"




container-build:
  stage: build
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build 
        --build-arg NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL 
        --build-arg AUTH0_SECRET=$AUTH0_SECRET
        --build-arg AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
        --build-arg AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
        --build-arg AUTH0_BASE_URL=$AUTH0_BASE_URL
        -t $CONTAINER_RULE_CRAFT 
        -t $CONTAINER_RULE_CRAFT_LATEST .
    - docker push $CONTAINER_RULE_CRAFT
    - docker push $CONTAINER_RULE_CRAFT_LATEST
  only:
    - dev
    - prod
    - main
  artifacts:
    expire_in: 1 week
    
deploy-dev:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy rulecraft"
    - kubectl -n smartergame-dev set image deployments/smartergame-rulecraft smartergame-rulecraft=$CONTAINER_RULE_CRAFT --record=true
    - kubectl -n smartergame-dev rollout status deployment smartergame-rulecraft
  only:
    - dev

deploy-prod:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy rulecraft"
    - kubectl -n smartergame-prod set image deployments/smartergame-rulecraft smartergame-rulecraft=$CONTAINER_RULE_CRAFT --record=true
    - kubectl -n smartergame-prod rollout status deployment smartergame-rulecraft
  only:
    - prod

container_scanning:
  dependencies:
    - container-build
  variables:
    CS_IMAGE: $CONTAINER_RULE_CRAFT
    CS_DOCKERFILE_PATH: Dockerfile
    GIT_STRATEGY: fetch
  artifacts:
    expire_in: 1 week
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

spotbugs-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

semgrep-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

gemnasium-maven-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

gemnasium-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

kics-iac-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

secret_detection:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'